import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import Projects from '../components/Projects'
import Skills from '../components/Skills'



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>CryRtex Portfolio Site</title>
        <meta name="description" content="Generated by CryRtex {bir gün güleriz}" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    <About />
    <Skills />
    <Projects />
    <Contact />
    </div>
  )
}

export default Home
